### ISSUE TITLE
Add "tablet" value to matchedDeviceType in useBreakpoint

### ISSUE THREAD

**Issue by cseas** [razorpay/blade#1203] opened 2023-05-25 07:25 UTC
# Problem

The [Blade docs][1] mention that `matchedDeviceType` considers screens below 768px as mobile and screens above it as desktop. This gives the impression that Blade design system advocates this convention as a requirement for projects that have responsive design.

Since the ground reality instead is that the decision for tablet designs is taken based on requirements and can vary product to product, the above API of `matchedDeviceType` leads to [confusion][2].

For projects such as the frontend-website, where the designers have taken a call to extend mobile designs till 1024px, devs need to create their own version of `matchedDeviceType` derived from `matchedBreakpoint` since the Blade implementation isn't flexible enough.

# Suggestion

Add a `"tablet"` value to `matchedDeviceType` that covers the 768px to 1023px screen range. This will both
- remove the need for Blade's consumer projects to create their own override of `matchedDeviceType`
- provide better readability for the intention of the breakpoint utilities used (see example code below)

```js
// this condition conveys that the project uses mobile designs for tablets too
matchedDeviceType === "mobile" || "tablet"
```

Alternate suggestion is to update the Blade useBreakpoint docs to indicate that creating a custom version of `matchedDeviceType` for your project is expected and encouraged based on design requirements to make it clear this isn't a deviation from design system standard.

[1]: https://blade.razorpay.com/?path=/docs/tokens-breakpoints--page#usebreakpoint-hook
[2]: https://razorpay.slack.com/archives/CMQ3RBHEU/p1684995362169019

**Comment by saurabhdaware** [comment] 2023-05-26 07:02
Added my opinions here - https://razorpay.slack.com/archives/CMQ3RBHEU/p1684997132416719?thread_ts=1684995362.169019&cid=CMQ3RBHEU

I think didn't reason my small tablet / large tablet opinion properly so adding it here

## Reasoning for smallTablet vs largeTablet differentiation

> Not sure if just returning tablet from matchedDeviceType would be enough because your responsive decisions can also change based on small tablet vs large tablet.

What I meant by this is, usually the horizontal UIs become vertical on small tablets (min-width: 768px (you might have seen this breakpoint a lot on internet)). The reason we have 1024px in razorpay.com might be mistake at a lot of places (I have probably contributed to it while working on new infra revamp 🙈 but I would do things differently if I am building them today).

Like the example you mentioned-
https://razorpay.slack.com/archives/CMQ3RBHEU/p1684995970065989?thread_ts=1684995362.169019&cid=CMQ3RBHEU

Here, only the image container part is shrinking and not the left container. It can be implemented as flex with 50% width on both containers, that way you'll have much more horizontally covered UI on large tablets and then you can break into vertical UI on small tablets (768px).

E.g. - 

https://github.com/razorpay/blade/assets/30949385/2d908b34-02b9-43b8-8519-339f073dc51a


As an experience, I would say the UI in left makes more sense than UI on the right

<table>
<tr><th>Horizontal UI on large tablet</th><th>Vertical UI on large tablet</th></tr>
<tr>
<td>
<img width="664" alt="image" src="https://github.com/razorpay/blade/assets/30949385/49816557-cabb-4b5e-9a37-24960d2ed9ef">
</td>
<td>
<img width="955" alt="image" src="https://github.com/razorpay/blade/assets/30949385/2dba6b26-2a69-42f1-8a83-73c9f1d9cac9">
</td>
</tr>
</table>


I would say this might be the case with lots of UIs. In the past, we didn't care much about the experience in tablets so we just switched to mobile UIs on large tablets itself because that is simpler but if you see a large tablet is 1024px which is quiet big horizontally to give a vertical UI experience.

At least in major pages like homepage, important payment pages, I feel we should have a little better UIs on large tablets. 


## Concerns with adding `tablet`

If you notice above, we're primarily making responsive differentiation not based on mobile vs desktop but small tablet vs large tablet. The moment you add `tablet` value, you end up removing that important breakpoint because now `device === 'mobile' && device === 'tablet` covers 0px to 1024px and `device === 'desktop' && device === 'tablet` covers 1024px + screens so we loose the ability to break the UI on 768px now which should be more common in terms of experience.

## Why not `smallTablet` and `largeTablet` values then

Well, then your checks would be come `device === 'mobile' || device === 'smallTablet' || device === 'largeTablet'` which seems as complex to me 🙈   

## Regarding unreadability of `xs`, `s` kind of tokens

I do agree with this. Added few reasonings in last point of this issue and last comment on why we had to do this -https://github.com/razorpay/blade/issues/1133#issuecomment-1517278492 

But yup this is still a grey area for me so happy to discuss if you have any ideas on this. For now we have added jsdoc comments with what value maps to which token.

**Comment by saurabhdaware** [comment] 2023-06-01 08:38
@anuraghazra @divyanshu013 @chaitanyadeorukhkar do add your opinions and thoughts here

**Comment by divyanshu013** [comment] 2023-06-01 11:31
- Agree on relying on matchedBreakpoint for a more granular control in this case, I think we can definitely do a better work on documenting usage guidelines for `useBreakpoint` (maybe in #1101)
- I understand the confusion around `xs`, `s`, etc. Adding to Saurabh's comment in #1133, an alternative is to have more semantic names here like `small-mobile`, `large-mobile`, `small-tablet`, `large-tablet`, `small-desktop`, etc. but the problem with this structure is it's difficult to create a logical progression of the sizes (is `large-tablet` smaller than `small-desktop` or not) plus a need for introducing more devices (eg. `medium-tablet`, `large-foldable`).
  - As an improvement we can document the breakpoints mapping better (current [docs](https://blade.razorpay.com/?path=/docs/tokens-breakpoints--page)), happy to hear more suggestions on what should be added but I was thinking an example on how to translate figma design responsively to start off with.

Lemme know if these two resolutions sound good ☝️

**Comment by kamleshchandnani** [comment] 2023-06-05 10:25
pretty much agree with the above points mentioned by @saurabhdaware 

>For projects such as the frontend-website, where the designers have taken a call to extend mobile designs till 1024px

@cseas the root cause lies here. Can we ask the designer the rationale behind this? if this is fixed then we are all good.

**Comment by saurabhdaware** [comment] 2023-06-05 10:32
Few more thoughts
- Should we support `matchedDeviceType`? It seems more of a work of Universe utils than Blade utils. Blade doesn't have access to architecture so it can't return correct `matchedDeviceType` in servers. In most cases it seems to be causing confusion to consumers that we "recommend" this as responsive solution but I think we don't right? As far as I understand, we recommend -
  - Using responsive styled props on normal blade components if they are supported
    ```jsx
    <Text marginTop={{ base: 'spacing.0', m: 'spacing.5' }} />
    ``` 
  - Writing a Box wrapper around and using responsive props 
    ```jsx
    <Box display={{ base: 'block', m: 'none' }}>
      <Text>Hi</Text>
    </Box>
    ```
  - Using CSS media queries on custom components using our breakpoint tokens
   ```js
    styled.button`
     @media (min-width: ${theme.breakpoints.m}px) {
        // mobile styles
      }
    `
    ```
- If we don't want to take the drastic step of removing `matchedDeviceType`, we can also add a note in documentation to discourage the use of it for responsive styling.

**Comment by saurabhdaware** [comment] 2023-07-28 04:50
I think the overall conclusion here is to not use 1024px for responsive designs as default. It should be 768px. Few elements can be subjectively responsive on 1024px and we have responsive props for that + useBreakpoint also returns breakpoints. 
But overall layout as a whole should not turn vertical on 1024px itself.

Closing this issue. Can reopen and discuss further if there's genuine case where entire page is expected to turn vertical on large tablets

**Closed by saurabhdaware** 2023-07-28 04:50 UTC
Labels: :thinking: Needs discussion
