### ISSUE TITLE
Date Picker component not opening

### ISSUE THREAD

**Issue by AnkitaBagale** [razorpay/blade#2214] opened 2024-05-31 10:55 UTC
There's a weird issue in date picker. calendar does not open on first load. Issue goes away if we refresh the page once and does not occur again during entire session. 

But issue happens again for next session.

Marking it as P0, as breaks the user experience.

https://github.com/razorpay/blade/assets/69760792/20e4d99d-10d4-4c72-abdf-f623e42d5c39

**Comment by anuraghazra** [comment] 2024-06-04 08:52
Can you share the code snippet? 

I'm unable to reproduce the bug: https://stackblitz.com/edit/hhwvwi?file=App.tsx

**Comment by AnkitaBagale** [comment] 2024-06-04 08:57
File path - https://github.com/razorpay/x/blob/budgets-v1/src/js/views/Budgets/Create/ValidityRangeSelector.tsx

**Comment by anuraghazra** [comment] 2024-06-04 09:10
Still unable to reproduce the bug, is it possible that it is happening because of the stale hot reload? 

Is this bug happening when you do this?:  

1. Stop dev server
2. Run the dev server
3. Open page

**Comment by AnkitaBagale** [comment] 2024-06-04 12:34
This is happening on deployed devstack label. we tried in incognito.
I checked with my team mate, she also faced the same issue.
Let me know if you want to connect to debug this

**Comment by sudhakar-selva** [comment] 2024-06-07 16:09
Seems like an good old stacking context issue 

**Scenario 1 - with issue**
When the user navigates from the home page to the budget creation page (where the datepicker is used), the route wrapper element (id = main-routes) has a z-index of 1, causing the datepicker to appear hidden even though it is open.

**Screenshots**

_route wrapper_
<img width="534" alt="Screenshot 2024-06-07 at 9 08 24 PM" src="https://github.com/razorpay/blade/assets/88188744/52f21464-ca63-46e2-90c8-bf4b3a4fada2">

_datepicker element_
<img width="535" alt="Screenshot 2024-06-07 at 9 11 44 PM" src="https://github.com/razorpay/blade/assets/88188744/ae0b07b8-aac7-4d86-864e-0bd919143ff0">

**Scenario 1 - without issue**
When the user directly visits the budget creation page, the route wrapper element doesn't have a z-index of 1, so the datepicker is visible.

**Screenshots**
> route wrapper
<img width="546" alt="Screenshot 2024-06-07 at 9 17 29 PM" src="https://github.com/razorpay/blade/assets/88188744/dc1fa6d2-2af6-4f2f-aa1b-948e51483f9f">


**Solution**
1. Reset the z-index for this route. @AnkitaBagale , this unblocks development.
2. @anuraghazra zIndex props seems to applied on datepicker root element, not on dialog element. is this expected behaviour? exposing z-index has its trade-off but might be useful for others. 
3. Can we, by default, assign a slightly higher z-index to all floating elements while ensuring it works as expected for modals and other elements? I would like to contribute to fixing this issue.

**Comment by anuraghazra** [comment] 2024-06-10 05:55
@sudhakar-selva oh interesting, good catch. 

> @anuraghazra zIndex props seems to applied on datepicker root element, not on dialog element. is this expected behaviour? 

Yes it has to be on the Popup element. 

> Can we, by default, assign a slightly higher z-index to all floating elements

Yeah we already do that for all Popover like elements, seems like we forgot to pass the zIndex to the correct wrapper. 
I've raised a fix for this: https://github.com/razorpay/blade/pull/2223

Thanks for debugging.

**Closed** 2024-06-10 11:16 UTC
Labels: P0
