### ISSUE TITLE
CSS specificity issues for components such as Modal, Divider

### ISSUE THREAD

**Issue by sudhakar-selva** [razorpay/blade#1607] opened 2023-09-06 09:13 UTC
[Slack](https://razorpay.slack.com/archives/CMQ3RBHEU/p1693991541721449)

Facing issue related to  css specificity when using blade components such as Modal, Divider and Bottom Sheet. eg:- Modal open styles specificity is lower than modal base styles, so when modal is opened its seems to render in wrong position(PFA)

[Steps to reproduce](https://github.com/razorpay/blade/issues/1607#issuecomment-1708386306)

**Screenshot**
<img width="926" alt="Screenshot 2023-09-06 at 12 38 29 AM" src="https://github.com/razorpay/blade/assets/88188744/c2f59b50-c4fb-4b5a-920f-2fffaaad904e">
<img width="620" alt="Screenshot 2023-09-06 at 12 58 52 AM" src="https://github.com/razorpay/blade/assets/88188744/d171f555-fe35-4176-9e26-e744c7c8fbff">

**Comment by anuraghazra** [comment] 2023-09-06 12:14
@sudhakar-selva can you give us a reproduction or link to the code so we can reproduce this?

**Comment by sudhakar-selva** [comment] 2023-09-06 13:37
@anuraghazra please follow this steps

1. devstack-label: blade-css
2. login as this merchant - https://dashboard.dev.razorpay.in/admin/merchants/LnZFkNWpMN3RoL
3. access https://x.dev.razorpay.in/line-of-credit/application
4. click on the get a revised offer CTA

please let me know, incase any issue. 

This page uses module federation and loads code from capital frontend, have tried replicating this in X(host) directly but didn't face any issues but module loaded by module federation causing this. Note: single styled-components instance might  be used by both X and capital frontend but blade version is different

Devstack configuration
**name: x-{{ .Values.devstack_label }}**
    image: 055e8c289b4567417249a9069db40696b1aa55f8
    capital_commit_id: f518bb5ba901b98a1596dd041045c6f930b60d80
    capital_onboarding_commit_id: efa8e8ff7157bfd6aa43d2b8ce4eacea3668b1d8

**Comment by anuraghazra** [comment] 2023-09-07 07:47
@sudhakar-selva unable to reproduce it. I have VPN connected also. 

<img width="1254" alt="image" src="https://github.com/razorpay/blade/assets/35374649/50edbc1b-0903-4ba6-8909-9a8c5b24ad6c">

**Comment by sudhakar-selva** [comment] 2023-09-07 09:55
@anuraghazra please clear cache and disable cache in network tab and try again. hope devstack label is enabled. please let me know if issue still there, we connect to resolve the same

**Comment by sudhakar-selva** [comment] 2023-09-11 05:51
@anuraghazra did it work? ^

**Comment by anuraghazra** [comment] 2023-09-11 05:52
@sudhakar-selva @snitin315 is picking this up today. 

@snitin315 maybe connect with him once to figure out the issue ^

**Comment by snitin315** [comment] 2023-09-13 00:22
@sudhakar-selva @anuraghazra I was able to reproduce this issue in a module federated setup. Working on a fix.

| Host App | Remote App |
| --------- | ------------- |
| <img width="1490" alt="Screenshot 2023-09-12 at 4 49 29 PM" src="https://github.com/razorpay/blade/assets/46647141/80a462ed-8d74-4870-90d0-b724512b03f7"> |  ![Screenshot 2023-09-12 at 4 49 39 PM](https://github.com/razorpay/blade/assets/46647141/0c51c8fd-bb4d-4843-a21a-0d29080eb8ef)|

**Comment by snitin315** [comment] 2023-09-13 02:47
I believe this is an issue in the module federation setup. I'll validate this once with @burhanuday

**Comment by snitin315** [comment] 2023-09-13 03:26
@sudhakar-selva Can you try the following two refactor one by one and check if it fixes your issue:

- Define `styled-component` as singleton.
- https://github.com/styled-components/styled-components/issues/2974#issuecomment-786990647

**Comment by snitin315** [comment] 2023-09-29 04:27
No follow-up, hence closing. Feel free to re-open if you are still facing issues.

**Comment by sudhakar-selva** [comment] 2024-03-12 09:32
> Define styled-component as singleton.
this would restrict us from independently  migrating to latest blade and currently we are only loading one version of styled-components on X dashboard through shared option on module federation(no warning from styled component regarding multiple version issue which we used to get before)

> https://github.com/styled-components/styled-components/issues/2974#issuecomment-786990647
this is already handled by fe-universe(https://github.com/razorpay/frontend-universe/blob/master/packages/universe-pack/src/configs/babel.react.js)

**Comment by sudhakar-selva** [comment] 2024-03-12 09:32
@snitin315 ^

**Comment by sudhakar-selva** [comment] 2024-03-12 10:20
using singleton, seems to have fixed the issue. but would there be any issues with this approach?

**Comment by saurabhdaware** [comment] 2024-03-18 06:56
> using singleton, seems to have fixed the issue. but would there be any issues with this approach?

No shouldn't be an issue. This will anyway be needed to avoid unexpected behaviour from multiple styled-component instances. Do test out the existing flows once before release.

Let me know if its still a problem

**Closed by saurabhdaware** 2024-03-18 06:56 UTC
Labels: bug, P0
