### ISSUE TITLE
CheckBoxGroup "defaultValues" prop change not reflecting with re-render

### ISSUE THREAD

**Issue by amandal97** [razorpay/blade#1659] opened 2023-09-20 11:37 UTC
Please consider the below implementation:
```
      <CheckboxGroup
        onChange={(e) => {
          props.updateAuthModes(e.values);
        }}
        defaultValue={props.route.auth}
      >
        {props.route.auth.map((authValue, index) => (
          <Checkbox
            key={index}
            size="medium"
            value={authValue}         
          >
            {authValue}
          </Checkbox>
        ))}
      </CheckboxGroup>
```
Here, when `props.route` changes, the consequent re-render is not picking up the new values provided to `defaultValue` prop. This might be because `defaultValue` is being set as a **local state** in [useControllable hook](https://github.com/razorpay/blade/blob/master/packages/blade/src/utils/useControllable.ts#L34C10-L34C20).

[Slack Thread](https://razorpay.slack.com/archives/C01H13RTF8V/p1695206991736829)

https://github.com/razorpay/blade/assets/45780866/73f1982a-9e1d-41cf-8a1a-4ae1a3257780

**Comment by anuraghazra** [comment] 2023-09-21 06:16
@amandal97 thanks for the issue, will get this fixed. 
if you are blocked, for now you can add a key prop to the CheckboxGroup to force rerender it. 

<CheckboxGroup key={props.route.auth} \/>

**Comment by anuraghazra** [comment] 2023-09-21 07:11
> when props.route changes, the consequent re-render is not picking up the new values provided to defaultValue prop.

@amandal97 actually this is an expected behaviour of uncontrolled components. 

Changing defaultValue won't change the input's value on consequent re-render, because defaultValue is like an initial value once it's set it won't change between renders. 
If you want the checkboxes to reflect changes between renders you need to switch to using controlled state. 

[Here's a codesandbox demo for understanding](https://codesandbox.io/s/hopeful-kilby-xhyjl4?file=/src/App.tsx)


**Solutions:**
 
- I think either you can use a controlled state
- Or use the `key` prop, this is also viable solution if you don't want to manage the state of the checkbox yourself.

**Comment by anuraghazra** [comment] 2023-09-22 06:20
Closing this as resolved, confirmed by @amandal97

**Closed by anuraghazra** 2023-09-22 06:20 UTC
