### ISSUE TITLE
TS Error using <BarChartAltIcon /> as a JSX component in TypeScript file

### ISSUE THREAD

**Issue by prem-io** [razorpay/blade#2035] opened 2024-02-22 07:08 UTC
When attempting to use the BarChartAltIcon in TypeScript JSX, the following error is encountered:

```
'BarChartAltIcon' cannot be used as a JSX component.
Its element type 'ReactElement<any, any> | Component<IconProps, any, any> | null' is not a valid JSX element.
Type 'Component<IconProps, any, any>' is not assignable to type 'Element | ElementClass | null'.
```
**Reproduction Steps:**

1. Include the relevant import statement for the BarChartAltIcon. `import { BarChartAltIcon } from '@razorpay/blade/components';`
2. Attempt to use <BarChartAltIcon /> in a TypeScript JSX file.
3. Observe the TypeScript error mentioned above.

<img width="800" alt="Screenshot 2024-02-22 at 12 34 08 PM" src="https://github.com/razorpay/blade/assets/51167082/ed78b64e-89e6-4a21-9dab-ce92b190ba00">

**Expected Behavior:**
The BarChartAltIcon should be usable as a JSX component without TypeScript errors.

**Environment:**
TypeScript version: "4.9.3"
React version: "17.0.2"
Blade: "10.18.0"

**Comment by saurabhdaware** [comment] 2024-02-22 07:33
Is it only happening with Box or in other components like CardBody as well?

Is it possible to replicate it on stackblitz? I tried but I am not getting any error there - 
https://stackblitz.com/edit/krkq6e?file=App.tsx,package.json,index.tsx

**Comment by saurabhdaware** [comment] 2024-02-29 09:41
@AniketOnWeb also faced this. We'll take a look

**Comment by anuraghazra** [comment] 2024-03-05 08:53
@prem-io @AniketOnWeb I tried to reproduce it in a fresh project, i was unable to reproduce this. 

But some observations: 
- The Dashboard CI typecheck isn't failing, neither the `tsc` command
- This is only happening inside the editor

If you could provide a minimal reproduction that would help debug this further. Until then this should not be blocker for development.

**Comment by snitin315** [comment] 2024-03-05 09:38
Closing as fixed on the [dashboard's master branch.](https://razorpay.slack.com/archives/C06BZ8D605A/p1709629367861529?thread_ts=1708689571.362969&cid=C06BZ8D605A)

**Closed by snitin315** 2024-03-05 09:38 UTC
Labels: bug, Icon, P0
