### ISSUE TITLE
`height` prop for Card component

### ISSUE THREAD

**Issue by InvincibleZeal** [razorpay/blade#1286] opened 2023-06-12 06:09 UTC
**Problem Statement** 

I built a carousel that has `Card` components as tiles. Since the `Card` API doesn't support `height` as a prop, I can't make it span the entire height of the parent `Carousel Slider` Box due to which the cards look uneven at different points. Setting a fixed height to a parent `Box` component looks weird for this use case. 

<img width="1290" alt="Screenshot 2023-06-12 at 11 32 26 AM" src="https://github.com/razorpay/blade/assets/42371840/ac0d9834-fd2c-4613-81a6-85a32f513743">

Check the implementation in [this PR](https://github.com/razorpay/frontend-website/pull/2160)

**Expectation**

Provide `height` as a prop on the `Card` and `CardBody` (for `justifyContent: space-between`) API so it can be set as 100% which will make it stretch over the Carousel Slider height making all the cards look even.

<img width="1291" alt="Screenshot 2023-06-12 at 11 32 12 AM" src="https://github.com/razorpay/blade/assets/42371840/41617fd6-684b-46ff-bb7b-c61ccc52dac4">

**Comment by nikhil-2911** [comment] 2023-06-20 10:02
Can you please assign this issue to me?

**Comment by chaitanyadeorukhkar** [comment] 2023-06-23 10:51
@InvincibleZeal you can have a Box inside CardBody with a fixed height, that should solve this, right? The dimensions of the Card should be decided by its content, having a Box of a specific height inside CardBody makes sense here

**Comment by cseas** [comment] 2023-06-23 12:51
Is there an issue with providing the height prop? Agree that there could be many different ways to work around this but we already have a workaround in place. Issue was created because developers experienced friction in implementing designs due to limitations in Blade API.

**Comment by chaitanyadeorukhkar** [comment] 2023-07-14 11:42
@cseas there is no issue with it but better to keep separation of concern. Since already have a layout component, it would be better if that takes care of such instances otherwise we will bloat up our component APIs for things that have straightforward solutions. Card with an empty body doesn't do much and will anyway always have some layout inside it. We can anyway consider adding this if we see more friction or more similar asks.

**Comment by PranjalMaithani** [comment] 2023-07-20 11:25
Same issue here. I have a flex/grid container which has 3 cards. I want to use flex with `space-between` on the card component to place the 'Know more' link at the bottom. But the issue is that the `CardBody` div is not occupying 100% of the height of the parent `Card` component.

![Screenshot 2023-07-20 at 2 51 09 PM](https://github.com/razorpay/blade/assets/75153839/81c47ffe-72e9-4d07-8aa2-d4cfd1d5e9f7)

**Comment by saurabhdaware** [comment] 2023-08-04 08:47
We discussed internally and decided to add height width properties on Card since its fairly common to change layout of card (We can probably add `minHeight`, `maxHeight`, `minWidth`, `maxWidth` properties as well.

Thanks for your inputs!

**Comment by snitin315** [comment] 2023-09-04 02:36
Card now supports `height` & `width` prop, added in [@razorpay/blade@10.2.0](https://github.com/razorpay/blade/releases/tag/%40razorpay%2Fblade%4010.2.0) , PR - https://github.com/razorpay/blade/pull/1508

**Closed by snitin315** 2023-09-04 02:36 UTC
Labels: enhancement, P1
